apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(AppName)
spec:
  replicas: $(NoOfReplicas)  
  selector:
    matchLabels:
      app: $(AppName)
  template:
    metadata:
      labels:
        app: $(AppName)
    spec:
      containers:
      - name: $(AppName)
        image: $(ContainerRegistry)/$(AppName):latest
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        env:
        - name: PORT
          value: "$(AppListenPort)"
        - name: MONGODB_URI
          #value: "mongodb://oneweb-dev:EdMFcE7YBiZLi9aPv83wXgtEZaurPufh2cteVEF9dEQ9Otmvg8oUWImU9KiAbOLcMli2Mu71Yg5gYO4O141Y9g%3D%3D@oneweb-dev.documents.azure.com:10255/crums?ssl=true&sslverifycertificate=false&replicaSet=globaldb"
          #value: $"mongodb://heroku_pw98r6t2:ndr17htr2jjtmpp1g0d6snrljf@ds343887.mlab.com:43887/heroku_pw98r6t2"
          value: $(MongoDBConnectionString)
        - name: HYDRA_URL
          value: $(HydraURL)
        - name: REDISCLOUD_URL
          value: $(CacheURL)
        - name: NODE_MODULES_CACHE
          value: "$(NodeModulesCacheTrueOrFalse)"
        ports:
        - containerPort: $(AppListenPort)
      - name: $(CacheName)
        image: $(CacheImage)
        ports:
        - containerPort: $(CacheListenPort)        
---
apiVersion: v1
kind: Service
metadata:
  name: $(AppName)
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-resource-group: $(StaticIPResourceGroup)
spec:
  type: LoadBalancer
#  backend:
#   serviceName: $(AppName)
#  externalName: uos-hydra-$(AppName)-dev.uksouth.cloudapp.azure.com
  selector:
    app: $(AppName)
  loadBalancerIP: $(ServiceStaticIP)
  ports:
   - name: http
     port: $(ServiceHTTPPort)
     targetPort: $(AppListenPort)
   - name: https
     port: $(ServiceHTTPSPort)
     targetPort: $(AppListenPort)

