apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperboy
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: paperboy
  template:
    metadata:
      labels:
        app: paperboy
    spec:
      containers:
      - name: paperboy
        image: onewebdev.azurecr.io/uosdev/paperboy:latest
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        env:
        - name: PORT
          value: 3000
        - name: MONGODB_URI
          #value: "mongodb://oneweb-dev:EdMFcE7YBiZLi9aPv83wXgtEZaurPufh2cteVEF9dEQ9Otmvg8oUWImU9KiAbOLcMli2Mu71Yg5gYO4O141Y9g%3D%3D@oneweb-dev.documents.azure.com:10255/crums?ssl=true&sslverifycertificate=false&replicaSet=globaldb"
          #value: $"mongodb://heroku_pw98r6t2:ndr17htr2jjtmpp1g0d6snrljf@ds343887.mlab.com:43887/heroku_pw98r6t2"
          value: mongodb://oneweb-dev:EdMFcE7YBiZLi9aPv83wXgtEZaurPufh2cteVEF9dEQ9Otmvg8oUWImU9KiAbOLcMli2Mu71Yg5gYO4O141Y9g%3D%3D@oneweb-dev.documents.azure.com:10255/crums?ssl=true&sslverifycertificate=false&replicaSet=globaldb
        - name: HYDRA_URL
          value: http://uos-hydra-dev.uksouth.cloudapp.azure.com
        - name: REDISCLOUD_URL
          value: redis://localhost:6379
        - name: NODE_MODULES_CACHE
          value: false          
        ports:
        - containerPort: 3000
      - name: paperboy-cache
        image: redis
        ports:
        - containerPort: 6379        
---
apiVersion: v1
kind: Service
metadata:
  name: paperboy
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-resource-group: onewebdev-static-ip-rg
spec:
  type: LoadBalancer
#  backend:
#   serviceName: paperboy
#  externalName: uos-hydra-paperboy-dev.uksouth.cloudapp.azure.com
  selector:
    app: paperboy
  loadBalancerIP: 52.151.66.139
  ports:
   - name: http
     port: 80
     targetPort: 3000
   - name: https
     port: 443
     targetPort: 3000